### ISSUE TITLE
Entrypoint "rei" is deprecated and must be changed to ensure future compatibility

### ISSUE THREAD

**Issue by SplendidAlakey** [Globox1997/RecipeRemover#1]
![2022-09-01_14 32 52](https://user-images.githubusercontent.com/86702831/187914719-3a4ce779-63a5-468d-9e5c-558ae1e47885.png)

I believe the only thing that needs changing is line 31 from "rei" to whatever you prefer out of the 3 new options instead in https://github.com/Globox1997/RecipeRemover/blob/1.19/src/main/resources/fabric.mod.json

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/RecipeRemover/commit/0eaa61febfb359df2daedb9b09439b53901856aa](https://github.com/Globox1997/RecipeRemover/commit/0eaa61febfb359df2daedb9b09439b53901856aa)
Will leave it open until I upload it to curseforge

**Comment by Globox1997** [comment]
Uploaded a new version to cf :)
