### ISSUE TITLE
Can still craft blacklisted modded items

### ISSUE THREAD

**Issue by GoopyXXV** [Globox1997/RecipeRemover#2]
Singleplayer world, no REI or other recipe viewers installed.

![image](https://user-images.githubusercontent.com/114884886/210104508-d718b186-dad8-4ad4-a678-33ba6752ccf3.png)

My Notepad++ font color is horrendous, I know

**Comment by Globox1997** [comment]
turn on printerrormessage and check what the log says while reloading datapacks

**Comment by Globox1997** [comment]
this mod takes the recipe id not the item id btw :) for further questions check out my discord
