### ISSUE TITLE
Crash preventing launch before attempting config

### ISSUE THREAD

**Issue by twenty41** [Globox1997/RecipeRemover#7]
### Minecraft Version

1.21

### Mod Loader Version

0.16.5

### Mod Version

1.0.8

### Describe the Issue

Adding the mod prevents game launch even before attempting to add any recipes

Thought it might be due to Recipe Book Is Pain conflicting but disabling that doesn't fix it

### latest.log

[latest.log](https://github.com/user-attachments/files/16970162/latest.log)

### Do you use any other mods except the required ones?

Yes, but **crash still happens on a brand new instance** with only RecipeRemover, Cloth Config API, Fabric API

[crash report from fresh instance](https://github.com/user-attachments/files/16970257/crash-2024-09-11_16.40.04-client.txt)

[latest.log from fresh instance](https://github.com/user-attachments/files/16970260/latest.log)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/RecipeRemover/commit/a1fd86a1f3249374a9760f9a239b151d4f8b0193](https://github.com/Globox1997/RecipeRemover/commit/a1fd86a1f3249374a9760f9a239b151d4f8b0193)
